<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>22a95ea8-dd78-4085-8f47-64a129e88a82</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoachHoopsAI.Application\CoachHoopsAI.Application.csproj" />
    <ProjectReference Include="..\CoachHoopsAI.Domain\CoachHoopsAI.Domain.csproj" />
    <ProjectReference Include="..\CoachHoopsAI.Infrastructure\CoachHoopsAI.Infrastructure.csproj" />
    <ProjectReference Include="..\CoachHoopsAI.Persistence\CoachHoopsAI.Persistence.csproj" />
  </ItemGroup>

</Project>
